version: '3.8'
services:
  web:
    container_name: ecommerce_frontend
    image: cinecus/ecommerce_frontend
    env_file:
      .env.local
    ports:
      - 3000:3000
    networks:
      - ecommerce
  api:
    container_name: ecommerce_api
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      .env
    ports:
      - 5000:5000
    networks:
      - ecommerce
  db:
    container_name: ecommerce_mongo
    image: mongo:4.4
    ports:
      - 5001:27017
    env_file:
      .env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
    networks:
      - ecommerce
networks:
  ecommerce: